[package]
name = "ray-tracer-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
image = { version = "0.24.4", default-features = false, features = ["png"] }
pretty_assertions = "1.3.0"
rayon = "1.5.3"
textwrap = "0.15.1"
